### ISSUE TITLE
elastic search

### ISSUE THREAD

**Issue by shubham1507** [aarav-tech/ems#4]
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/snj/.virtualenvs/ems/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/snj/.virtualenvs/ems/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/snj/.virtualenvs/ems/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/snj/.virtualenvs/ems/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/snj/.virtualenvs/ems/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/snj/.virtualenvs/ems/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/snj/.virtualenvs/ems/lib/python3.6/site-packages/django_elasticsearch_dsl/__init__.py", line 3, in <module>
    from .documents import Document  # noqa
  File "/home/snj/.virtualenvs/ems/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 7, in <module>
    from elasticsearch_dsl import Document as DSLDocument
ImportError: cannot import name 'Document'

**Comment by raikk** [comment]
refer 

https://github.com/elastic/elasticsearch-dsl-py/issues/1273#issuecomment-555725177
